[package]
name = "pylon_core"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
futures = "0.3.26"
magic-wormhole = "0.6.0"
serde = "1.0.152"
thiserror = "1.0.38"
url = "2.3.1"
